### ISSUE TITLE
`gradle generatePojo` fails w/ Spring error

### ISSUE THREAD

**Issue by NfNitLoop** [graphql-java-generator/graphql-gradle-plugin-project#10]
I can run: 

    gradle generateClient

And that completes successfully.  But I might just want to use the POJOs because I can't introduce Spring as a dependency to the project I'm working on.

But, when I try to run:

    gradle generatePojo
    
I get an error:

> \> Task :generatePojo FAILED
> Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'addRelayConnections': Unsatisfied dependency expressed through field 'documentParser'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'generateCodeDocumentParser': Unsatisfied dependency expressed through field 'configuration'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.graphql_java_generator.plugin.conf.CommonConfiguration' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
> 
> FAILURE: Build failed with an exception.
> 
> \* What went wrong:
> Execution failed for task ':generatePojo'.
> \> Error creating bean with name 'addRelayConnections': Unsatisfied dependency expressed through field 'documentParser'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'generateCodeDocumentParser': Unsatisfied dependency expressed through field 'configuration'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.graphql_java_generator.plugin.conf.CommonConfiguration' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by etienne-sf** [comment]
Ok, I repeated it. 

This suprises me, as there is a project that uses the `generatePojo` goal.

I'll try to deliver a patch this week end.

Etienne
