### ISSUE TITLE
Release v1.14

### ISSUE THREAD

**Issue by gjvoosten** [graphql-java-generator/graphql-gradle-plugin-project#2]
Now graphql-maven-plugin (and graphql-java-runtime) [v1.14 has been released](https://github.com/graphql-java-generator/graphql-maven-plugin-project/blob/master/CHANGELOG.md#114), please also release the corresponding v1.14 of the Gradle plugin so us Gradle users can upgrade as well. :pleading_face:

**Comment by etienne-sf** [comment]
You're right

I published the 1.14 just when I started my (real) work. 
So I published the Gradle plugin only once I've done for what I'm paid...

It's now done.

Etienne
