### ISSUE TITLE
Field graphQlClient in de.mine.generated.util.MutationsExecutor required a bean of type 'org.springframework.graphql.client.GraphQlClient' that could not be found.

### ISSUE THREAD

**Issue by Erando89** [graphql-java-generator/graphql-gradle-plugin-project#22]
Hi Étienne,
thank you for your hard work on this project. I followed your [Client Gradle tutorial](https://github.com/graphql-java-generator/GraphQL-Forum-Gradle-Tutorial-client) and ran in some problems which I'm not sure you're aware of.

I used your plugin successfully to generate a client of a GraphQL API (using Spring Boot 2.4.4 btw). I copied all generated files into my project and added one dependency:

`implementation "com.graphql-java-generator:graphql-java-client-runtime:2.4"`

Thus all files could get compiled. When starting the application though I get this exception and the app terminates:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field graphQlClient in de.mine.generated.util.MutationsExecutor required a bean of type 'org.springframework.graphql.client.GraphQlClient' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
	- @org.springframework.beans.factory.annotation.Qualifier("httpGraphQlClient")


Action:

Consider defining a bean of type 'org.springframework.graphql.client.GraphQlClient' in your configuration.
```

Thank you for looking into this.

Best regards

**Comment by etienne-sf** [comment]
Hum,

If I understand well, you executed these steps:
* Configure a project with the plugin and your graphqls schema
* Generate the code 
* report it into another, unlinked project

Right ?

Then did you also copy the generated resources folder ? It contains an autoconfiguration spring files, that is mandatory to make this work.

Etienne

**Comment by etienne-sf** [comment]
Any update ?

**Comment by etienne-sf** [comment]
Hello,

Thanks to your detailed info, I'll try to repeat this issue.

Currently, I'm having a hard time just compiling the project. My PC seems to be quite reluctant about your gradle conf
:(

**Comment by etienne-sf** [comment]
Yes it definitely doesn't want : I upgraded java to version 21, gradle to 8.8, and I'm back to this error : `Could not resolve all artifacts for configuration ':detachedConfiguration1'.`
I'll keep on testing tomorrow

**Comment by thomson90** [comment]
No hurry.
If you have found a working combination of a gradle configuration, I would be very happy. It doesn't necessarily have to be the very latest Java, gradle or Spring version.

I am very glad that you want to solve the problem.

**Comment by etienne-sf** [comment]
I definitely can't reproduce this issue.
Can you precise the plugin's configuration ?
(that is: your `graphql.gradle` file)

**Comment by thomson90** [comment]
Hi Etienne,
i have solved this Problem...

> Field springContextBean in de.myCompany.myProject.gitlab.spring_autoconfiguration.GraphQLPluginAutoConfiguration required a bean of type 'com.graphql_java_generator.client.SpringContextBean' that could not be found.
> 
> Action:
> Consider defining a bean of type 'com.graphql_java_generator.client.SpringContextBean' in your configuration.

with the ComponentScan Annotation on of my Config-Classes:
`@ComponentScan(basePackages = { "com.graphql_java_generator.client" }) `

I think that the classes that were autogenerated could not call the SpringContextBean of the client package. Unfortunately, I have other problems with the migration. I will rebuild my project so that I can publish it on Gitlab and keep you in the loop.

**Comment by etienne-sf** [comment]
Hello,

I created a project from your ´build.gradle´ and ´graph.gradle´ files. 

But I could not locate this code (that you provided):

´´´ java 
private ObjectResponse getObjectResponse(String queryResponseDef) throws GraphQLRequestPreparationException {
    return new Builder(graphQlClient, GraphQLRequest.class).withQueryResponseDef(queryResponseDef).build();
  }
´´´ 

From where did you copy this code ?

Étienne

**Comment by thomson90** [comment]
Sorry for the confusion. The code was written by myself in my project and uses your builder constructor. I thought the changes in your `new Builder`-constructor where responsible for the problem mentioned above i was able to fix the original problem by setting the correct annotation:  
```
@SpringBootApplication(scanBasePackageClasses = { Application.class, GraphqlClientUtils.class, QueryExecutor.class })
```

I was unable to reproduce @Erando89's error. Maybe he forgot the correct Annotation too. From my point of view, this issue can be closed.

**Comment by etienne-sf** [comment]
Right, ok.

That explains why I didn't find this code.


BTW, I don't understand why you had to create a `GraphQlClient` yourself. The plugin generates a spring autoconfiguration file, that creates the needed GraphQlClient. So you should not have to create it yourself. Please note that:
* Two `httpGraphQlClientAllGraphQLCases` are created: `httpGraphQlClient` (for queries and mutations) and `webSocketGraphQlClient` (for subscriptions)
* if you're using bean suffix, these generated `GraphQlClient` are suffixed with this bean suffix

I added a note in my todo list, to check that this is properly documented.

Etienne
