### ISSUE TITLE
How to secure Websocket connection for subscriptions?

### ISSUE THREAD

**Issue by fschmuck** [graphql-java-generator/graphql-gradle-plugin-project#7]
Is there an easy way with this plugin to secure the websocket connection via spring-security?

**Comment by etienne-sf** [comment]
Hello,

This is already available.

You can check the [WebSecurityConfiguration](https://github.com/graphql-java-generator/graphql-gradle-plugin-project/blob/master/graphql-gradle-plugin-samples-allGraphQLCases-server/src/main/java/org/allGraphQLCases/server/oauth2/WebSecurityConfiguration.java) class, in the `graphql-gradle-plugin-samples-allGraphQLCases-server` module.
This module is both a demo, and a way to execute integration tests when building the project.
This class provide OAuth authorization, based on the `org.springframework.security` package.

[This page](https://github.com/graphql-java-generator/graphql-maven-plugin-project/wiki/client_oauth2) on the wiki give the associated information.

Etienne

**Comment by fschmuck** [comment]
Thank you for the quick reply.
I figured out how to secure the connection to the websocket but when i send a GraphQL request my SecurityContext does not have a authorization set. So i cannot check on permission within my datafetchers.
Is there also an example for this case?

**Comment by etienne-sf** [comment]
Sorry, I can't help your that far.
