### ISSUE TITLE
Websocket connnection with Sec-WebSocket-Protocol: graphql-ws header

### ISSUE THREAD

**Issue by fschmuck** [graphql-java-generator/graphql-gradle-plugin-project#8]
Does the current implementation support the **Sec-WebSocket-Protocol: graphql-ws** header?
Because when I want to establish a connection with this header from my frontend-client the connection will be closed instantly.

**Comment by etienne-sf** [comment]
Hum, I am afraid I missed something there. 

Yes, the low level is not properly implemented. 
It works when both sides (client and server) are generated code by the plug-in. 
But it won't work with another (standard) implementation. 

I'll work quickly on this one. 
But it will take some days. 

Étienne

**Comment by fschmuck** [comment]
Thank you very much.

Would it be a viable approach to implement the SubProtocolCapable interface on the generated WebsocketHandler and set allowed subprotocols via the plugin configuration?

**Comment by etienne-sf** [comment]
It seems a good idea, as it would allow a retro-compatibility with the existing code. 
There is currently no way to add a new protocol per configuration in the plug-in. So this would need a patch. 

That being said, AFAIK, the current and only protocol that is really managed is the graphql-transport-ws protocol, as specified by [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md). 
Are we speaking about the same thing ?

Étienne

**Comment by fschmuck** [comment]
Yes, right.

**Comment by etienne-sf** [comment]
No news on this issue, since the delivery of the `graphql-transport-ws`.

Closing this issue
