### ISSUE TITLE
Support for triple-quoted comments?

### ISSUE THREAD

**Issue by NfNitLoop** [graphql-java-generator/graphql-gradle-plugin-project#9]
Your README.md says:

> Comments coming from the GraphQL schema are reported in the generated code

And that does seem to work for `# comments like this`.

But I'm working with a schema generated by graphql-js's [printSchema] function, which outputs:

```
"""comments like this"""

"""
and sometimes
like
this
"""
```

It would be nice if that were supported too.  Though maybe this is just a case of that library doing the wrong thing?  (I couldn't find any documentation about using such strings as documentation/comments in GraphQL SDL.)

Thanks for this library!

[printSchema]: https://graphql.org/graphql-js/utilities/#printschema

**Comment by etienne-sf** [comment]
Hum,

I'm the 'responsible' for reading the comments. The graphql-java library is.

And according the [GraphQL Spec](file:///C:/APPLIRTE64/appli/Mes%20Sites%20Web/graphql%20(spec%20juin%202018)/spec.graphql.org/June2018/index.html#sec-Comments), comments are marked with a `#`


I'll check that. 

But I think it's up to graphql-java:
* If it reads those samples as a comment, then the plugin will find them as comments, and use them.
* If it doesn't read those comments, then the plugin won't even know they exist


Did you try to change these comments at the exact same place in the schema, to check if it actually works ?

Etienne

**Comment by etienne-sf** [comment]
graphql-java still can't read these comments. 
And it's not a valid syntax according to the GraphQL specifications. I guess that graphql-java will take it into account as soon as the specification does. Then it will be ok for the plug-in. 

I close this issue.

**Comment by steven-sheehy** [comment]
The spec does allow for single or double quoted comments. The spec differentiates between `#` line comments and `"` or `"""` block comments. The latter is the [official](https://spec.graphql.org/October2021/#sec-Descriptions) way to provide descriptions for types, fields, arguments, etc. Graphql-java also supports single or triple quotes for descriptions and [recommends](https://github.com/graphql-java/graphql-java/issues/2390#issuecomment-864889890) that over the legacy `#` comments.

@etienne-sf Can we re-open this and consider supporting quoted comments?

**Comment by etienne-sf** [comment]
Oups I missed this one

Yes, if it's not entirely treated, you can re-open it. 

But then I'm sad: I thought it was ok. 

Étienne

**Comment by steven-sheehy** [comment]
Unfortunately, I don't have permission to re-open. Can you or @NfNitLoop re-open it?
